# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
#  theme_night: minimal
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'U.C. Santa Cruz'
    description: "Amin Karbas's Personal Website"
    twitter: 'OItsMAK2'
  analytics:
    google_analytics: 'UA-162785927-1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Mohammadamin Karbasforushan'
    license:
      enable: false
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - golang
      - c
      - c++
      - python
      - latex
  math:
    enable: true
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/AKarbas/akarbas.github.io-source'
    content_dir: content
    branch: master
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: ''
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
#  cms:
#    branch: master
#    local_backend: false
#  isotope:
#    # Enable if you use the Portfolio widget or Publication filter
#    enable: true
  academicons:
    enable: true
